Reporting
ktindiana/sphinxval pull request #6
Opened 2023-10-02 21:33 UTC by lukestegeman

Fixed __pycache__ issue.

Integrated reporting module into SPHINX workflow. Allows for reporting only mode (sphinxval.sphinx.validate() is not called) with use of --ReportOnly command-line option.

2023-10-02 21:47 UTC, ktindiana commented
Add module in bin to run report standalone

2023-10-11 20:10 UTC, lukestegeman commented
@rickyegeland
Batch files have been removed from the reporting branch and the .gitignore was updated.

2023-10-17 15:34 UTC, rickyegeland requested changes

2023-10-17 15:34 UTC, rickyegeland commented on requirements-reporting.txt
I don't want a separate requirements.txt for a particular feature of sphinxval.  Aim to update the existing requirements.txt with what is required for the reporting to work.

On that note, are these very new versions really required for the reporting to work?  Is there a more minimal upgrade from the previous requirements.txt that would be sufficient?

2023-10-17 17:24 UTC, lukestegeman commented on sphinxval/utils/config.py
For clarification, my directory structure looks like this (per @ktindiana's instructions):

```
code/
    data/
    lists/
    model/
    output/
    plots/
    reference/
    sphinxval/
        bin/
           ...
        sphinxval/
            sphinx/
            utils/
                ...
                config.py
                ...
    validation_reports/
```

so, running `python bin/sphinx.py` will point to `code/data/`. Should I switch up my directory structure so that `data/`, `lists/`, `model/`, `output/`, `plots/`, `reference/`, and `validation_reports/` are inside `sphinxval/`?

2023-10-17 17:27 UTC, lukestegeman commented on requirements-reporting.txt
I've updated the requirements.txt with module versions needed when using Python 3.10.5. No upgrades to current dependencies need to be made. `markdown 3.5` and `PyPDF2 3.0.1` are the new requirements for the reporting module.

2023-10-17 17:37 UTC, lukestegeman commented on sphinxval/utils/config.py
***...inside `code/sphinxval/`?

2023-10-17 18:38 UTC, rickyegeland commented on sphinxval/utils/config.py
I would say yes, and I think @ktindiana agreed on Teams.  We should add those data directories to `.gitignore` too.

The justification is that it is good practice for a code to do its job within the directory where it lives, and not create/delete directories outside its sandbox unless there is an established standard (e.g. Linux /etc, /share) or the user specifies it by altering the config file.  Bad things could happen if a user happened to decide to deploy the code in a place where `../data` already existed from some other work.

2023-10-17 18:51 UTC, rickyegeland commented
I don't see any outstanding issues with this pull request.  Once Luke confirms he is satisfied, I suggest that Katie go ahead and merge it.

2023-10-17 18:51 UTC, rickyegeland approved these changes

2023-10-17 19:12 UTC, merged